const SHOP_URL = 'https://brewandbrewsco.com/products';
const questions = [
  {key:'drink',title:'What do you normally drink?',help:'Choose one or more. Your matches update immediately.',multi:true,options:[['Black coffee','black'],['Latte','latte'],['Espresso','espresso'],['Drip coffee','drip'],['Cold brew','cold-brew'],['French press','french-press'],['Pour over','pour-over'],['Sweet coffee drink','syrup']]},
  {key:'taste',title:'What sounds best in your cup?',help:'Select every flavor or feeling that appeals to you.',multi:true,options:[['Smooth','smooth'],['Bold','bold'],['Chocolatey','chocolate'],['Nutty','nutty'],['Sweet','sweet'],['Bright','bright'],['Fruity','fruity'],['Earthy','earthy'],['Low acidity','low-acid'],['Strong','strong']]},
  {key:'additions',title:'How do you usually take it?',help:'This helps us choose coffees that stay balanced in your cup.',multi:true,options:[['Black','black'],['Cream','cream'],['Milk','latte'],['Sugar','sweet'],['Flavored syrup','syrup'],['Depends on the day','balanced']]},
  {key:'brew',title:'How do you make coffee?',help:'Choose the equipment you use most often.',multi:true,options:[['Drip machine','drip'],['Espresso machine','espresso'],['French press','french-press'],['Pour over','pour-over'],['Cold brew','cold-brew'],['Reusable pod','drip'],['I buy it prepared','balanced']]},
  {key:'form',title:'How would you like your coffee?',help:'This won’t change taste matching, but it prepares the final choice.',multi:false,options:[['Whole bean','whole-bean'],['Ground','ground'],['Not sure yet','balanced']]}
];
let coffees=[];let step=0;let answers={};let wheelTurns=0;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
async function init(){document.querySelectorAll('[data-shop-link]').forEach(a=>a.href=SHOP_URL);try{coffees=await fetch('data/coffees.json').then(r=>r.json())}catch{coffees=[]}bind();renderLive();}
function bind(){document.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;({start:startQuiz,next:next,back:back,skip:next,restart:restart,home:home,roulette:roulette,spin:spin}[action]||(()=>{}))();});}
function show(id){$$('.screen').forEach(s=>s.classList.remove('active'));$('#screen-'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function home(){show('start')}function restart(){step=0;answers={};startQuiz()}function roulette(){show('roulette')}
function startQuiz(){show('quiz');renderQuestion()}
function renderQuestion(){const q=questions[step];$('#step-label').textContent=`Step ${step+1} of ${questions.length}`;$('#question-title').textContent=q.title;$('#question-help').textContent=q.help;$('#progress-fill').style.width=`${((step+1)/questions.length)*100}%`;const selected=answers[q.key]||[];$('#choices').innerHTML=q.options.map(([label,val])=>`<button class="choice ${selected.includes(val)?'selected':''}" data-value="${val}"><span>${label}</span></button>`).join('');$$('.choice').forEach(btn=>btn.onclick=()=>toggle(q,btn.dataset.value));renderLive();}
function toggle(q,val){let arr=answers[q.key]||[];if(q.multi){arr=arr.includes(val)?arr.filter(x=>x!==val):[...arr,val]}else{arr=[val]}answers[q.key]=arr;renderQuestion()}
function next(){if(step<questions.length-1){step++;renderQuestion()}else{renderResults();show('results')}}function back(){if(step>0){step--;renderQuestion()}else home()}
function selectedTags(){return Object.values(answers).flat()}
function scoreCoffee(c){const tags=selectedTags();let s=30;tags.forEach(t=>{if(c.tags.includes(t))s+=10;else if((t==='bold'&&c.body>=8)||(t==='smooth'&&c.acidity<=4)||(t==='sweet'&&c.sweetness>=7)||(t==='strong'&&c.body>=9)||(t==='bright'&&c.acidity>=6))s+=7;else s-=1});return Math.max(35,Math.min(99,s))}
function ranked(){return coffees.filter(c=>c.active).map(c=>({...c,score:scoreCoffee(c)})).sort((a,b)=>b.score-a.score)}
function adventurePick(exclude=[]){return ranked().filter(c=>!exclude.includes(c.id)).sort((a,b)=>b.adventure-a.adventure)[0]||ranked()[0]}
function renderLive(){if(!coffees.length||!$('#live-match-list'))return;const top=ranked().slice(0,3);$('#live-match-list').innerHTML=top.map((c,i)=>`<div class="mini-match"><span class="rank">${i+1}</span><div><b>${c.name}</b><small>${c.roast} · ${c.flavors.slice(0,2).join(' · ')}</small></div><span class="score">${c.score}%</span></div>`).join('');const a=adventurePick(top.map(x=>x.id));$('#live-adventure').innerHTML=`<small>ADVENTURE PICK</small><b>${a.name}</b><p>${a.flavors.join(' · ')}</p>`}
function renderResults(){const top=ranked().slice(0,3);$('#result-grid').innerHTML=top.map((c,i)=>`<article class="result-card"><span class="match-badge">${i===0?'BEST MATCH':`MATCH ${i+1}`} · ${c.score}%</span><h3>${c.name}</h3><small>${c.roast} roast</small><div class="flavors">${c.flavors.map(f=>`<span>${f}</span>`).join('')}</div><p>${c.summary}</p><p><b>Why we chose it:</b> ${c.why}</p><a class="card-link" href="${c.url==='#'?SHOP_URL:c.url}">View coffee →</a></article>`).join('');const a=adventurePick(top.map(x=>x.id));$('#adventure-result').innerHTML=`<div><p class="eyebrow">Step outside your usual</p><h3>${a.name}</h3><p>${a.why} Flavors: ${a.flavors.join(', ')}.</p></div><a class="primary ghost-link" href="${a.url==='#'?SHOP_URL:a.url}">Take the adventure →</a>`}
function spin(){if(!coffees.length)return;const wheel=$('#wheel');wheelTurns+=5+Math.floor(Math.random()*3);wheel.style.transform=`rotate(${wheelTurns*360+Math.floor(Math.random()*320)}deg)`;const active=coffees.filter(c=>c.active);const pick=active[Math.floor(Math.random()*active.length)];const card=$('#roulette-card');card.innerHTML='<p class="eyebrow">Spinning…</p><h3>Finding your coffee.</h3><p>The wheel is choosing from the Brew & Brews lineup.</p>';setTimeout(()=>{card.innerHTML=`<p class="eyebrow">Roulette chose</p><h3>${pick.name}</h3><p><b>${pick.roast} roast</b></p><div class="flavors">${pick.flavors.map(f=>`<span>${f}</span>`).join('')}</div><p>${pick.summary}</p><a class="card-link" href="${pick.url==='#'?SHOP_URL:pick.url}">I’ll try it →</a>`},3500)}
init();
